version: '3.7'
services:
  app:
    build: ./app
    container_name: app
  app2:
    build: ./app2
    container_name: app2
  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - app